### ISSUE TITLE
Running chisurf on MacOS

### ISSUE THREAD

**Issue by AndersBarth** [Fluorescence-Tools/chisurf#38]
Hi Thomas,

the latest Mac release of ChiSurf is quite old, and I would like to use the newest version natively on Mac.

Here is what I did:

1. Clone the repository.
2. Make a new conda environment from the environment.yml file.
3. Activate this environment.
4. Run `python setup.py install`
5. Run `chisurf` from terminal.

Here is the error I get.
```
(chisurf) Anders@Anders-MBP chisurf % chisurf
Traceback (most recent call last):
  File "/Users/Anders/opt/anaconda3/envs/chisurf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2458, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'chisurf.gui' has no attribute 'gui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Anders/opt/anaconda3/envs/chisurf/bin/chisurf", line 11, in <module>
    load_entry_point('chisurf==19.9.22', 'gui_scripts', 'chisurf')()
  File "/Users/Anders/opt/anaconda3/envs/chisurf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/Anders/opt/anaconda3/envs/chisurf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/Users/Anders/opt/anaconda3/envs/chisurf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/Users/Anders/opt/anaconda3/envs/chisurf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2460, in resolve
    raise ImportError(str(exc))
ImportError: module 'chisurf.gui' has no attribute 'gui'
```

Not sure what is going wrong. I also tried running chisurf from code (base.py), but I get import errors.

What did I do wrong?

**Comment by tpeulen** [comment]
I recommend using the released versions. The last macOS release is fairly new (2017). Since then, the software did not reach a stage where I feel comfortable to make a new release.
